---
deployment:
  tasks:
    - name: Set DEPLOYPATH
      command: export DEPLOYPATH=/home/nutorla3/repositories/REWORKED/

    - name: Copy files to DEPLOYPATH
      command: /bin/cp -r * $DEPLOYPATH
