name: Publish Next.js App to cPanel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build Next.js app
        run: |
          npm ci
          npm run build

      - name: Deploy to cPanel
        uses: jakejarvis/cpanel-git-deploy@4.3.1
        with:
          cpanel-username: ${{ secrets.FTP_USERNAME }}
          cpanel-password: ${{ secrets.FTP_PASSWORD }}
          cpanel-domain: ${{ secrets.FTP_SERVER }}
          cpanel-directory: public_html
